# -*- coding: utf-8 -*-
"""TelecomX_BR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155arg4eV_NeIGJkEQkIUEMsoBiCbQNXe

#📌 Extracão
"""

import requests
import pandas as pd

url = 'https://raw.githubusercontent.com/alura-cursos/challenge2-data-science/refs/heads/main/TelecomX_Data.json'
response = requests.get(url)
data = response.json()
df = pd.DataFrame(data)

print(df.head())

"""#🔧 Transformação"""



"""#📊 Carga e análise"""



"""#📄Relatorio Final"""

